---
name: check kb_urls

on:
  push:
    paths:
      - .github/workflows/check_urls.yml
      - "server/kb_urls.csv"
  pull_request:
    paths:
      - .github/workflows/check_urls.yml
      - "server/kb_urls.csv"

jobs:
  url-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare url file
        run: cat server/kb_urls.csv | cut -d ',' -f1 >kb_urls.txt
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --timeout 20 --no-progress kb_urls.txt
